name: "Soft Secret"
description: "🍦Write client ids and keys from github secret, api fetch, or plain text into a file for build actions."
author: "Plasmo Corp."
branding:
  icon: cloud-lightning
  color: orange

inputs:
  secret:
    description: "The content of the secret, could be github secret itself."
    required: true
  content:
    description: "Alias of secret."
    required: false
  input:
    description: "Alias of secret."
    required: false

  fetch:
    description: "Whether the secret need to be fetched."
    required: false
  is-url:
    description: "Alias of fetch."
    required: false

  target:
    description: "Relative path to the target file to write secret to."
    required: true
  output:
    description: "Alias of target."
    required: false

runs:
  using: "node16"
  main: "index.js"
